openapi: 3.0.0
info:
  title: API Documentation Practice
  description: Optional multiline or single-line description in
               [CommonMark](http://commonmark.org/help/) or HTML.
  version: '3.0'
  termsOfService: ''
   
servers:
  - url: /
paths:
  /health:
    get:
      tags:
      - health
      responses:
        '200':    # status code
          description: OK